-- Vithya Traders live Supabase delta snapshot
-- Captured read-only from project kssydapdfmkfufrqhwzp on 2026-10-03.
-- Purpose: preserve pre-freeze Purchase/Inventory experimental scaffolding and
-- main-system objects newer than supabase/schema.sql.
-- IMPORTANT: recovery/reference snapshot only; NOT the approved Platform V2 schema.
-- Contains schema only, no business data or secrets.

BEGIN;

-- -----------------------------------------------------------------------------
-- TABLE: public.analytics_data_quality_issue
CREATE TABLE public.analytics_data_quality_issue (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  domain text NOT NULL,
  source_object text,
  issue_type text NOT NULL,
  severity text DEFAULT 'WARN'::text NOT NULL,
  entity_key text,
  detail text,
  status text DEFAULT 'OPEN'::text NOT NULL,
  detected_at timestamp with time zone DEFAULT now() NOT NULL,
  resolved_at timestamp with time zone,
  resolved_by text,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  CONSTRAINT analytics_data_quality_issue_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_dq_severity_ck CHECK (severity = ANY (ARRAY['INFO'::text, 'WARN'::text, 'ERROR'::text, 'CRITICAL'::text])),
  CONSTRAINT analytics_dq_status_ck CHECK (status = ANY (ARRAY['OPEN'::text, 'ACKNOWLEDGED'::text, 'RESOLVED'::text, 'IGNORED'::text]))
);
ALTER TABLE public.analytics_data_quality_issue ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_analytics_dq_open ON public.analytics_data_quality_issue USING btree (domain, status, severity);
COMMENT ON TABLE public.analytics_data_quality_issue IS "Central data-quality queue for Purchase and Inventory analytics and PO lifecycle reconciliation.";

-- -----------------------------------------------------------------------------
-- TABLE: public.analytics_refresh_log
CREATE TABLE public.analytics_refresh_log (
  run_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  dataset text NOT NULL,
  started_at timestamp with time zone DEFAULT now() NOT NULL,
  finished_at timestamp with time zone,
  source_max_date date,
  rows_written bigint,
  status text DEFAULT 'running'::text NOT NULL,
  error_text text,
  details jsonb DEFAULT '{}'::jsonb NOT NULL,
  CONSTRAINT analytics_refresh_log_pkey PRIMARY KEY (run_id)
);
ALTER TABLE public.analytics_refresh_log ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.analytics_refresh_log IS "Refresh/freshness audit for shared Purchase and Inventory analytical datasets.";

-- -----------------------------------------------------------------------------
-- TABLE: public.data_sync_state
CREATE TABLE public.data_sync_state (
  source_name text NOT NULL,
  last_source_id text,
  last_source_loaded_at timestamp with time zone,
  last_sync_at timestamp with time zone,
  source_row_count bigint,
  synced_row_count bigint,
  status text,
  details jsonb DEFAULT '{}'::jsonb NOT NULL,
  CONSTRAINT data_sync_state_pkey PRIMARY KEY (source_name)
);
ALTER TABLE public.data_sync_state ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- TABLE: public.expense_register_data
CREATE TABLE public.expense_register_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  branch_id text,
  date text,
  vendor_id_db text,
  vendor_name text,
  expense_no text,
  invoice_no text,
  gst_register_type text,
  gstin text,
  reverse_charge text,
  tax_type text,
  gst_type text,
  description text,
  total_basic text,
  discount text,
  total_tax text,
  round_off text,
  gross_total text,
  tcs_amount text,
  tds_amount text,
  basic_0 text,
  basic_5 text,
  basic_12 text,
  basic_18 text,
  basic_28 text,
  basic_other text,
  tax_5 text,
  tax_12 text,
  tax_18 text,
  tax_28 text,
  tax_other text,
  cgst text,
  sgst text,
  igst text,
  payment_data text,
  created_on text,
  created_by text,
  location text,
  source text DEFAULT 'FTP'::text,
  loaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expense_register_data_expense_no_key UNIQUE (expense_no),
  CONSTRAINT expense_register_data_pkey PRIMARY KEY (id)
);
ALTER TABLE public.expense_register_data ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- TABLE: public.inventory_demand_exception_review
CREATE TABLE public.inventory_demand_exception_review (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  transaction_key text NOT NULL,
  parent_sku text NOT NULL,
  sales_date date,
  voucher_no text,
  customer_key text,
  customer_name text,
  qty numeric,
  net_value numeric,
  detection_method text,
  statistical_score numeric,
  review_status text DEFAULT 'Pending'::text NOT NULL,
  baseline_exclude boolean DEFAULT false NOT NULL,
  reviewed_by text,
  reviewed_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT inventory_demand_exception_review_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_demand_exception_review_review_status_check CHECK (review_status = ANY (ARRAY['Pending'::text, 'Normal'::text, 'Recurring Bulk'::text, 'Exceptional'::text, 'Project'::text, 'Ignore'::text])),
  CONSTRAINT inventory_demand_exception_review_transaction_key_key UNIQUE (transaction_key)
);
ALTER TABLE public.inventory_demand_exception_review ENABLE ROW LEVEL SECURITY;
CREATE INDEX ix_exception_parent_sku ON public.inventory_demand_exception_review USING btree (parent_sku);
COMMENT ON TABLE public.inventory_demand_exception_review IS "Human review of statistically unusual sales orders; only baseline_exclude=true removes demand from normalized baseline.";

-- -----------------------------------------------------------------------------
-- TABLE: public.inventory_settings
CREATE TABLE public.inventory_settings (
  id smallint DEFAULT 1 NOT NULL,
  stock_reliable boolean DEFAULT false NOT NULL,
  use_stock_in_reorder boolean DEFAULT false NOT NULL,
  default_service_level numeric(5,4) DEFAULT 0.9500 NOT NULL,
  default_target_coverage_days integer DEFAULT 30 NOT NULL,
  xyz_x_max_cv numeric(8,4) DEFAULT 0.5000 NOT NULL,
  xyz_y_max_cv numeric(8,4) DEFAULT 1.0000 NOT NULL,
  demand_pattern_adi_cutoff numeric(8,4) DEFAULT 1.3200 NOT NULL,
  demand_pattern_cv2_cutoff numeric(8,4) DEFAULT 0.4900 NOT NULL,
  fsn_fast_active_months_min integer DEFAULT 9 NOT NULL,
  fsn_slow_active_months_min integer DEFAULT 3 NOT NULL,
  fsn_nonmoving_days integer DEFAULT 180 NOT NULL,
  analytics_history_months integer DEFAULT 36 NOT NULL,
  notes text,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT inventory_settings_default_service_level_check CHECK (default_service_level > 0::numeric AND default_service_level < 1::numeric),
  CONSTRAINT inventory_settings_default_target_coverage_days_check CHECK (default_target_coverage_days >= 0),
  CONSTRAINT inventory_settings_id_check CHECK (id = 1),
  CONSTRAINT inventory_settings_pkey PRIMARY KEY (id)
);
ALTER TABLE public.inventory_settings ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.inventory_settings IS "Global inventory analytics controls. Stock/reorder usage is gated here; defaults intentionally keep unreliable stock out of reorder decisions.";

-- -----------------------------------------------------------------------------
-- TABLE: public.inventory_sku_analytics
CREATE TABLE public.inventory_sku_analytics (
  parent_sku text NOT NULL,
  as_of_date date NOT NULL,
  source_max_sales_date date,
  product_name text,
  category text,
  subcategory text,
  brand text,
  history_months integer,
  demand_30d numeric,
  demand_90d numeric,
  demand_3m numeric,
  demand_6m numeric,
  demand_12m numeric,
  demand_24m numeric,
  avg_3m numeric,
  avg_6m numeric,
  avg_12m numeric,
  avg_24m numeric,
  median_monthly_12m numeric,
  active_months_12m integer,
  zero_months_12m integer,
  transactions_12m bigint,
  selling_days_12m bigint,
  days_since_last_sale integer,
  avg_days_between_sales numeric,
  median_days_between_sales numeric,
  monthly_sd_12m numeric,
  cv_12m numeric,
  cv2_12m numeric,
  adi_months_12m numeric,
  abc_class text,
  abc_revenue_class text,
  abc_basis text,
  xyz_class text,
  fsn_class text,
  demand_pattern text,
  trend_3v6_pct numeric,
  trend_6v12_pct numeric,
  yoy_pct numeric,
  trend_class text,
  unique_customers_12m bigint,
  top1_customer_pct numeric,
  top3_customer_pct numeric,
  top5_customer_pct numeric,
  customer_hhi numeric,
  customer_concentration_class text,
  anonymous_qty_pct numeric,
  exceptional_order_count_12m bigint DEFAULT 0 NOT NULL,
  exceptional_qty_12m numeric DEFAULT 0 NOT NULL,
  exceptional_pct_12m numeric DEFAULT 0 NOT NULL,
  baseline_demand_12m numeric,
  new_sku_flag boolean DEFAULT false NOT NULL,
  reactivated_flag boolean DEFAULT false NOT NULL,
  demand_confidence text,
  safety_stock_qty numeric,
  reorder_point_qty numeric,
  target_stock_qty numeric,
  recommended_buy_qty numeric,
  purchase_urgency text,
  recommendation_reason text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  demand_fy numeric,
  demand_prev_fy numeric,
  last_sale_date date,
  p75_monthly_12m numeric,
  p90_monthly_12m numeric,
  exceptional_candidate_count_12m bigint,
  reviewed_exceptional_count_12m bigint,
  raw_demand_12m numeric,
  stock_qty numeric,
  stock_loaded_at timestamp with time zone,
  stock_reliability text,
  open_po_qty numeric,
  in_transit_qty numeric,
  pending_not_shipped_qty numeric,
  next_expected_receipt date,
  lead_time_days_used numeric,
  service_level_used numeric,
  effective_moq numeric,
  effective_pack_multiple numeric,
  inventory_position_qty numeric,
  recommendation_status text,
  CONSTRAINT inventory_sku_analytics_pkey PRIMARY KEY (parent_sku)
);
ALTER TABLE public.inventory_sku_analytics ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_inventory_analytics_abc ON public.inventory_sku_analytics USING btree (abc_class);
CREATE INDEX idx_inventory_analytics_fsn ON public.inventory_sku_analytics USING btree (fsn_class);
CREATE INDEX idx_inventory_analytics_pattern ON public.inventory_sku_analytics USING btree (demand_pattern);
CREATE INDEX idx_inventory_analytics_urgency ON public.inventory_sku_analytics USING btree (purchase_urgency);
CREATE INDEX idx_inventory_analytics_xyz ON public.inventory_sku_analytics USING btree (xyz_class);
COMMENT ON TABLE public.inventory_sku_analytics IS "Current Stage-2 inventory demand intelligence by Parent SKU; reorder fields remain nullable until stock/policy inputs are trustworthy.";
COMMENT ON COLUMN public.inventory_sku_analytics.baseline_demand_12m IS "Normalized 12-month demand after subtracting only reviewed rows where baseline_exclude=true.";
COMMENT ON COLUMN public.inventory_sku_analytics.raw_demand_12m IS "Raw 12-month positive sales demand before confirmed exceptional/project exclusions.";
COMMENT ON COLUMN public.inventory_sku_analytics.recommendation_status IS "Controls whether reorder output is actionable. Current global settings keep stock-based recommendations blocked until stock is approved as reliable.";

-- -----------------------------------------------------------------------------
-- TABLE: public.inventory_sku_monthly_demand
CREATE TABLE public.inventory_sku_monthly_demand (
  parent_sku text NOT NULL,
  month_start date NOT NULL,
  qty numeric DEFAULT 0 NOT NULL,
  sales_value numeric DEFAULT 0 NOT NULL,
  bill_count bigint DEFAULT 0 NOT NULL,
  selling_days bigint DEFAULT 0 NOT NULL,
  unique_known_customers bigint DEFAULT 0 NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT inventory_sku_monthly_demand_pkey PRIMARY KEY (parent_sku, month_start)
);
ALTER TABLE public.inventory_sku_monthly_demand ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.inventory_sku_monthly_demand IS "Monthly positive sales demand by Parent SKU for trend, XYZ, FSN and demand-pattern analysis. Missing months mean zero demand.";

-- -----------------------------------------------------------------------------
-- TABLE: public.inventory_sku_policy
CREATE TABLE public.inventory_sku_policy (
  parent_sku text NOT NULL,
  criticality text DEFAULT 'Unclassified'::text NOT NULL,
  service_level_target numeric(5,4),
  target_coverage_days integer,
  min_base_stock_qty numeric,
  max_stock_override_qty numeric,
  safety_stock_override_qty numeric,
  reorder_point_override_qty numeric,
  do_not_stock boolean DEFAULT false NOT NULL,
  discontinue boolean DEFAULT false NOT NULL,
  substitute_group text,
  manual_monthly_demand_qty numeric,
  stock_reliable_override boolean,
  policy_notes text,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT inventory_sku_policy_criticality_check CHECK (criticality = ANY (ARRAY['Vital'::text, 'Essential'::text, 'Desirable'::text, 'Unclassified'::text])),
  CONSTRAINT inventory_sku_policy_pkey PRIMARY KEY (parent_sku),
  CONSTRAINT inventory_sku_policy_service_level_target_check CHECK (service_level_target IS NULL OR service_level_target > 0::numeric AND service_level_target < 1::numeric),
  CONSTRAINT inventory_sku_policy_target_coverage_days_check CHECK (target_coverage_days IS NULL OR target_coverage_days >= 0)
);
ALTER TABLE public.inventory_sku_policy ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.inventory_sku_policy IS "Manual per-parent-SKU inventory rules and overrides.";

-- -----------------------------------------------------------------------------
-- TABLE: public.po_audit
CREATE TABLE public.po_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_at timestamp with time zone DEFAULT now() NOT NULL,
  user_name text,
  action text NOT NULL,
  entity text,
  entity_id text,
  field_name text,
  old_value text,
  new_value text,
  note text,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  CONSTRAINT po_audit_pkey PRIMARY KEY (id)
);
ALTER TABLE public.po_audit ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_po_audit_entity ON public.po_audit USING btree (entity, entity_id);
CREATE INDEX idx_po_audit_event_at ON public.po_audit USING btree (event_at DESC);
COMMENT ON TABLE public.po_audit IS "Append-only Supabase mirror of meaningful PO workflow changes from the Apps Script Audit Log.";

-- -----------------------------------------------------------------------------
-- TABLE: public.po_headers
CREATE TABLE public.po_headers (
  po_number text NOT NULL,
  real_po_no text,
  request_no text,
  supplier_key text,
  supplier_name text,
  status text,
  created_at timestamp with time zone,
  approved_at timestamp with time zone,
  sent_at timestamp with time zone,
  supplier_acknowledged_at timestamp with time zone,
  promised_date date,
  revised_promised_date date,
  snooze_until date,
  bill_at timestamp with time zone,
  closed_at timestamp with time zone,
  closed_by text,
  cancelled_at timestamp with time zone,
  cancel_reason text,
  notes jsonb DEFAULT '[]'::jsonb NOT NULL,
  source_updated_at timestamp with time zone,
  synced_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT po_headers_pkey PRIMARY KEY (po_number)
);
ALTER TABLE public.po_headers ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.po_headers IS "Supabase mirror of PO-level lifecycle facts from the Purchase Dashboard/Apps Script.";

-- -----------------------------------------------------------------------------
-- TABLE: public.po_lines
CREATE TABLE public.po_lines (
  po_line_key text NOT NULL,
  po_number text NOT NULL,
  request_line_id text,
  parent_sku text,
  item_code text,
  product_name text,
  lane text,
  ordered_qty numeric DEFAULT 0 NOT NULL,
  cancelled_qty numeric DEFAULT 0 NOT NULL,
  unit_rate numeric,
  tax_rate numeric,
  line_status text,
  line_note text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT po_lines_pkey PRIMARY KEY (po_line_key),
  CONSTRAINT po_lines_po_number_fkey FOREIGN KEY (po_number) REFERENCES po_headers(po_number) ON DELETE CASCADE
);
ALTER TABLE public.po_lines ENABLE ROW LEVEL SECURITY;
CREATE INDEX ix_po_lines_parent_sku ON public.po_lines USING btree (parent_sku);
CREATE INDEX ix_po_lines_po_number ON public.po_lines USING btree (po_number);
COMMENT ON TABLE public.po_lines IS "Supabase mirror of PO line facts using stable PO Line Key and canonical Parent SKU.";

-- -----------------------------------------------------------------------------
-- TABLE: public.po_receipt_lines
CREATE TABLE public.po_receipt_lines (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  receipt_id text NOT NULL,
  po_line_key text,
  parent_sku text,
  item_code text,
  product_name text,
  lane text,
  received_qty numeric DEFAULT 0 NOT NULL,
  accepted_qty numeric,
  rejected_qty numeric DEFAULT 0 NOT NULL,
  returned_qty numeric DEFAULT 0 NOT NULL,
  price numeric,
  CONSTRAINT po_receipt_lines_pkey PRIMARY KEY (id),
  CONSTRAINT po_receipt_lines_po_line_key_fkey FOREIGN KEY (po_line_key) REFERENCES po_lines(po_line_key) ON DELETE SET NULL,
  CONSTRAINT po_receipt_lines_receipt_id_fkey FOREIGN KEY (receipt_id) REFERENCES po_receipts(receipt_id) ON DELETE CASCADE,
  CONSTRAINT po_receipt_lines_receipt_id_po_line_key_item_code_key UNIQUE (receipt_id, po_line_key, item_code)
);
ALTER TABLE public.po_receipt_lines ENABLE ROW LEVEL SECURITY;
CREATE INDEX ix_po_receipt_lines_parent_sku ON public.po_receipt_lines USING btree (parent_sku);
CREATE INDEX ix_po_receipt_lines_po_line_key ON public.po_receipt_lines USING btree (po_line_key);
COMMENT ON TABLE public.po_receipt_lines IS "One row per received product line; supports accepted/rejected/returned quantities.";

-- -----------------------------------------------------------------------------
-- TABLE: public.po_receipts
CREATE TABLE public.po_receipts (
  receipt_id text NOT NULL,
  po_number text NOT NULL,
  shipment_id text,
  real_po_no text,
  received_date date,
  bill_mi_no text,
  received_by text,
  source_logged_at timestamp with time zone,
  synced_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT po_receipts_pkey PRIMARY KEY (receipt_id),
  CONSTRAINT po_receipts_po_number_fkey FOREIGN KEY (po_number) REFERENCES po_headers(po_number) ON DELETE CASCADE,
  CONSTRAINT po_receipts_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES po_shipments(shipment_id) ON DELETE SET NULL
);
ALTER TABLE public.po_receipts ENABLE ROW LEVEL SECURITY;
CREATE INDEX ix_po_receipts_po_number ON public.po_receipts USING btree (po_number);
CREATE INDEX ix_po_receipts_shipment_id ON public.po_receipts USING btree (shipment_id);
COMMENT ON TABLE public.po_receipts IS "One row per receipt event.";

-- -----------------------------------------------------------------------------
-- TABLE: public.po_shipment_lines
CREATE TABLE public.po_shipment_lines (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  shipment_id text NOT NULL,
  po_number text NOT NULL,
  line_index integer,
  po_line_key text,
  parent_sku text,
  item_code text,
  product_name text,
  qty_shipped numeric DEFAULT 0 NOT NULL,
  gst_qty numeric,
  nongst_qty numeric,
  bill_rate numeric,
  tax_rate numeric,
  mrp numeric,
  selling_price numeric,
  return_qty numeric DEFAULT 0 NOT NULL,
  flags text[],
  source_updated_at timestamp with time zone,
  created_by text,
  CONSTRAINT po_shipment_lines_pkey PRIMARY KEY (id),
  CONSTRAINT po_shipment_lines_po_line_key_fkey FOREIGN KEY (po_line_key) REFERENCES po_lines(po_line_key) ON DELETE SET NULL,
  CONSTRAINT po_shipment_lines_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES po_shipments(shipment_id) ON DELETE CASCADE,
  CONSTRAINT po_shipment_lines_shipment_id_line_index_key UNIQUE (shipment_id, line_index)
);
ALTER TABLE public.po_shipment_lines ENABLE ROW LEVEL SECURITY;
CREATE INDEX ix_po_shipment_lines_parent_sku ON public.po_shipment_lines USING btree (parent_sku);
CREATE INDEX ix_po_shipment_lines_po_line_key ON public.po_shipment_lines USING btree (po_line_key);
COMMENT ON TABLE public.po_shipment_lines IS "One row per product line within a shipment/lot.";

-- -----------------------------------------------------------------------------
-- TABLE: public.po_shipments
CREATE TABLE public.po_shipments (
  shipment_id text NOT NULL,
  po_number text NOT NULL,
  lot_no text,
  shipped_date date,
  expected_delivery_date date,
  transport text,
  lr_no text,
  bill_gst text,
  bill_nongst text,
  mi_ready_at date,
  received_at date,
  uploaded_at date,
  vasy_bill_no text,
  round_off_gst numeric,
  round_off_nongst numeric,
  charges jsonb DEFAULT '[]'::jsonb NOT NULL,
  totals jsonb DEFAULT '{}'::jsonb NOT NULL,
  shipment_note text,
  source_updated_at timestamp with time zone,
  created_by text,
  synced_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT po_shipments_pkey PRIMARY KEY (shipment_id),
  CONSTRAINT po_shipments_po_number_fkey FOREIGN KEY (po_number) REFERENCES po_headers(po_number) ON DELETE CASCADE
);
ALTER TABLE public.po_shipments ENABLE ROW LEVEL SECURITY;
CREATE INDEX ix_po_shipments_po_number ON public.po_shipments USING btree (po_number);
COMMENT ON TABLE public.po_shipments IS "One row per real shipment/lot.";

-- -----------------------------------------------------------------------------
-- TABLE: public.po_sku_analytics
CREATE TABLE public.po_sku_analytics (
  parent_sku text NOT NULL,
  as_of_date date NOT NULL,
  po_count_12m bigint,
  open_po_qty numeric,
  in_transit_qty numeric,
  pending_not_shipped_qty numeric,
  received_qty_12m numeric,
  median_first_receipt_lead_days numeric,
  p90_first_receipt_lead_days numeric,
  median_full_receipt_lead_days numeric,
  p90_full_receipt_lead_days numeric,
  lead_sd_days numeric,
  lead_sample_count bigint,
  fill_rate_pct numeric,
  otif_pct numeric,
  partial_delivery_pct numeric,
  avg_lots_per_po numeric,
  next_expected_receipt date,
  oldest_open_po_days integer,
  active_supply_sources integer,
  single_source boolean,
  supply_confidence text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT po_sku_analytics_pkey PRIMARY KEY (parent_sku)
);
ALTER TABLE public.po_sku_analytics ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.po_sku_analytics IS "Supplier-neutral PO execution metrics by Parent SKU for Inventory consumption.";

-- -----------------------------------------------------------------------------
-- TABLE: public.purchase_buyer_override
CREATE TABLE public.purchase_buyer_override (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  parent_sku text NOT NULL,
  decision_date date DEFAULT CURRENT_DATE NOT NULL,
  request_no text,
  po_number text,
  system_recommended_qty numeric,
  final_buy_qty numeric NOT NULL,
  delta_qty numeric GENERATED ALWAYS AS ((final_buy_qty - COALESCE(system_recommended_qty, (0)::numeric))) STORED,
  reason_code text,
  reason_notes text,
  selected_supplier_key text,
  selected_supplier_name text,
  selected_rate numeric,
  system_context jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_by text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT purchase_buyer_override_pkey PRIMARY KEY (id)
);
ALTER TABLE public.purchase_buyer_override ENABLE ROW LEVEL SECURITY;
CREATE INDEX ix_override_parent_sku ON public.purchase_buyer_override USING btree (parent_sku);
COMMENT ON TABLE public.purchase_buyer_override IS "Audit trail of buyer overrides to system-recommended purchase quantity.";

-- -----------------------------------------------------------------------------
-- TABLE: public.purchase_request_lines
CREATE TABLE public.purchase_request_lines (
  line_id text NOT NULL,
  request_no text,
  requested_at timestamp with time zone,
  user_name text,
  request_type text,
  urgency text,
  new_product boolean,
  parent_sku text,
  item_code text,
  product_name text,
  requested_qty numeric DEFAULT 0 NOT NULL,
  line_comment text,
  submission_comment text,
  status text,
  source_updated_at timestamp with time zone,
  synced_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT purchase_request_lines_pkey PRIMARY KEY (line_id)
);
ALTER TABLE public.purchase_request_lines ENABLE ROW LEVEL SECURITY;
CREATE INDEX ix_purchase_request_lines_parent_sku ON public.purchase_request_lines USING btree (parent_sku);
CREATE INDEX ix_purchase_request_lines_status ON public.purchase_request_lines USING btree (status);
COMMENT ON TABLE public.purchase_request_lines IS "Supabase mirror of PO Request line workflow. Preserves No Stock / Stock Planning / Customer Order demand signals for Purchase and Inventory.";

-- -----------------------------------------------------------------------------
-- TABLE: public.purchase_sku_analytics
CREATE TABLE public.purchase_sku_analytics (
  parent_sku text NOT NULL,
  as_of_date date NOT NULL,
  source_max_purchase_date date,
  product_name text,
  category text,
  subcategory text,
  brand text,
  purchase_qty_3m numeric,
  purchase_qty_6m numeric,
  purchase_qty_12m numeric,
  purchase_qty_24m numeric,
  purchase_qty_fy numeric,
  purchase_value_3m numeric,
  purchase_value_6m numeric,
  purchase_value_12m numeric,
  purchase_value_24m numeric,
  purchase_value_fy numeric,
  purchase_events_6m bigint,
  purchase_events_12m bigint,
  purchase_events_24m bigint,
  last_purchase_date date,
  last_purchase_qty numeric,
  last_purchase_rate numeric,
  avg_purchase_qty_12m numeric,
  median_purchase_qty_12m numeric,
  min_purchase_qty_12m numeric,
  max_purchase_qty_12m numeric,
  mode_purchase_qty_12m numeric,
  avg_days_between_purchases numeric,
  median_days_between_purchases numeric,
  wavg_rate_3m numeric,
  wavg_rate_6m numeric,
  wavg_rate_12m numeric,
  min_rate_12m numeric,
  max_rate_12m numeric,
  median_rate_12m numeric,
  price_change_vs_wavg_3m_pct numeric,
  price_change_vs_wavg_6m_pct numeric,
  price_change_vs_wavg_12m_pct numeric,
  supplier_count_12m integer,
  primary_supplier_key text,
  primary_supplier_name text,
  primary_supplier_pct numeric,
  top2_supplier_pct numeric,
  supplier_hhi numeric,
  single_source boolean,
  inferred_moq numeric,
  inferred_pack_multiple numeric,
  inference_confidence text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  days_since_last_purchase integer,
  po_count_12m bigint,
  avg_lead_days numeric,
  median_lead_days numeric,
  p75_lead_days numeric,
  p90_lead_days numeric,
  lead_sd_days numeric,
  lead_sample_count bigint,
  fill_rate_pct numeric,
  otif_pct numeric,
  partial_delivery_pct numeric,
  cancellation_pct numeric,
  avg_lots_per_po numeric,
  open_po_qty numeric,
  in_transit_qty numeric,
  pending_not_shipped_qty numeric,
  next_expected_receipt date,
  oldest_open_po_days integer,
  effective_moq numeric,
  effective_pack_multiple numeric,
  supply_confidence text,
  supply_risk_class text,
  CONSTRAINT purchase_sku_analytics_pkey PRIMARY KEY (parent_sku)
);
ALTER TABLE public.purchase_sku_analytics ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_purchase_analytics_single_source ON public.purchase_sku_analytics USING btree (single_source);
COMMENT ON TABLE public.purchase_sku_analytics IS "Current Purchase Register analytics by Parent SKU.";
COMMENT ON COLUMN public.purchase_sku_analytics.po_count_12m IS "Actual PO count from PO Tracking, not purchase-register bill/event count.";
COMMENT ON COLUMN public.purchase_sku_analytics.open_po_qty IS "Outstanding ordered quantity from live PO lifecycle, net of received/cancelled quantity.";
COMMENT ON COLUMN public.purchase_sku_analytics.supply_confidence IS "Confidence in PO/supplier performance metrics based on usable completed-PO sample size and date completeness.";

-- -----------------------------------------------------------------------------
-- TABLE: public.purchase_sku_policy
CREATE TABLE public.purchase_sku_policy (
  parent_sku text NOT NULL,
  default_moq numeric(18,4),
  default_pack_multiple numeric(18,4),
  preferred_order_cycle_days integer,
  supply_risk_override text,
  policy_notes text,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  planning_lead_days_override numeric,
  planning_supply_sources_override integer,
  single_source_override boolean,
  CONSTRAINT purchase_sku_policy_pkey PRIMARY KEY (parent_sku),
  CONSTRAINT purchase_sku_policy_risk_ck CHECK (supply_risk_override IS NULL OR (supply_risk_override = ANY (ARRAY['LOW'::text, 'MEDIUM'::text, 'HIGH'::text, 'CRITICAL'::text])))
);
ALTER TABLE public.purchase_sku_policy ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.purchase_sku_policy IS "Supplier-neutral purchase planning rules for Inventory. Existing default_moq/default_pack_multiple are the planning MOQ/pack fields.";

-- -----------------------------------------------------------------------------
-- TABLE: public.purchase_sku_supplier_analytics
CREATE TABLE public.purchase_sku_supplier_analytics (
  parent_sku text NOT NULL,
  supplier_key text NOT NULL,
  supplier_name text,
  as_of_date date NOT NULL,
  qty_12m numeric,
  value_12m numeric,
  purchase_events_12m bigint,
  last_purchase_date date,
  last_purchase_qty numeric,
  last_rate numeric,
  wavg_rate_12m numeric,
  min_rate_12m numeric,
  max_rate_12m numeric,
  median_rate_12m numeric,
  avg_purchase_qty_12m numeric,
  median_purchase_qty_12m numeric,
  mode_purchase_qty_12m numeric,
  po_count_12m bigint,
  avg_lead_days numeric,
  median_lead_days numeric,
  p75_lead_days numeric,
  p90_lead_days numeric,
  lead_sd_days numeric,
  lead_sample_count bigint,
  fill_rate_pct numeric,
  otif_pct numeric,
  partial_delivery_pct numeric,
  cancellation_pct numeric,
  avg_lots_per_po numeric,
  open_po_qty numeric,
  in_transit_qty numeric,
  pending_not_shipped_qty numeric,
  next_expected_receipt date,
  oldest_open_po_days integer,
  confirmed_moq numeric,
  inferred_moq numeric,
  pack_multiple numeric,
  supply_confidence text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  qty_3m numeric,
  qty_6m numeric,
  qty_24m numeric,
  value_3m numeric,
  value_6m numeric,
  value_24m numeric,
  wavg_rate_3m numeric,
  wavg_rate_6m numeric,
  price_change_vs_wavg_3m_pct numeric,
  price_change_vs_wavg_6m_pct numeric,
  CONSTRAINT purchase_sku_supplier_analytics_pkey PRIMARY KEY (parent_sku, supplier_key)
);
ALTER TABLE public.purchase_sku_supplier_analytics ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_purchase_supplier_supplier ON public.purchase_sku_supplier_analytics USING btree (supplier_key);
COMMENT ON TABLE public.purchase_sku_supplier_analytics IS "Current commercial and supply-performance analytics by Parent SKU x supplier.";

-- -----------------------------------------------------------------------------
-- TABLE: public.purchase_sku_supplier_policy
CREATE TABLE public.purchase_sku_supplier_policy (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  parent_sku text NOT NULL,
  supplier_key text NOT NULL,
  supplier_name text,
  is_primary boolean DEFAULT false NOT NULL,
  is_approved boolean DEFAULT true NOT NULL,
  confirmed_moq numeric,
  pack_multiple numeric,
  committed_lead_days numeric,
  preferred_order_cycle_days integer,
  minimum_order_value numeric,
  payment_terms text,
  policy_notes text,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT purchase_sku_supplier_policy_parent_sku_supplier_key_key UNIQUE (parent_sku, supplier_key),
  CONSTRAINT purchase_sku_supplier_policy_pkey PRIMARY KEY (id)
);
ALTER TABLE public.purchase_sku_supplier_policy ENABLE ROW LEVEL SECURITY;
CREATE INDEX ix_supplier_policy_parent_sku ON public.purchase_sku_supplier_policy USING btree (parent_sku);
COMMENT ON TABLE public.purchase_sku_supplier_policy IS "Manual SKU x supplier commercial/supply constraints such as MOQ, pack and committed lead time.";

-- -----------------------------------------------------------------------------
-- TABLE: public.sku_alias_map
CREATE TABLE public.sku_alias_map (
  item_code text NOT NULL,
  parent_sku text NOT NULL,
  lane text DEFAULT 'UNKNOWN'::text NOT NULL,
  product_name text,
  source_system text,
  first_seen_date date,
  last_seen_date date,
  active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT sku_alias_lane_ck CHECK (lane = ANY (ARRAY['GST'::text, 'NON_GST'::text, 'UNKNOWN'::text])),
  CONSTRAINT sku_alias_map_pkey PRIMARY KEY (item_code)
);
ALTER TABLE public.sku_alias_map ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_sku_alias_parent ON public.sku_alias_map USING btree (parent_sku);
COMMENT ON TABLE public.sku_alias_map IS "Traceability map from every ERP item code to canonical parent_sku and GST/non-GST lane.";

-- -----------------------------------------------------------------------------
-- TABLE: public.sku_master
CREATE TABLE public.sku_master (
  parent_sku text NOT NULL,
  product_name text NOT NULL,
  department text,
  category text,
  sub_category text,
  brand text,
  sub_brand text,
  uom text,
  gst_item_code text,
  nongst_item_code text,
  mapping_status text DEFAULT 'AUTO'::text NOT NULL,
  active boolean DEFAULT true NOT NULL,
  source text DEFAULT 'SUPABASE_SEED'::text NOT NULL,
  first_seen_date date,
  last_seen_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT sku_master_mapping_status_ck CHECK (mapping_status = ANY (ARRAY['AUTO'::text, 'VERIFIED'::text, 'MANUAL'::text, 'REVIEW'::text])),
  CONSTRAINT sku_master_pkey PRIMARY KEY (parent_sku)
);
ALTER TABLE public.sku_master ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.sku_master IS "Canonical physical-SKU master shared by Purchase and Inventory. GST/non-GST ERP codes consolidate to parent_sku.";

-- -----------------------------------------------------------------------------
-- TABLE: public.supplier_master
CREATE TABLE public.supplier_master (
  supplier_key text NOT NULL,
  supplier_id text,
  supplier_name text NOT NULL,
  gst_type text,
  gstin text,
  pan_no text,
  supplier_type text,
  phone text,
  whatsapp text,
  email text,
  city text,
  state text,
  active boolean DEFAULT true NOT NULL,
  source text DEFAULT 'VASY'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  default_lane text,
  default_lead_days numeric(12,3),
  notes text,
  source_updated_at timestamp with time zone,
  CONSTRAINT supplier_master_pkey PRIMARY KEY (supplier_key)
);
ALTER TABLE public.supplier_master ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX idx_supplier_master_id ON public.supplier_master USING btree (supplier_id) WHERE (supplier_id IS NOT NULL);
COMMENT ON TABLE public.supplier_master IS "Canonical supplier lookup for Purchase and PO tracking. Supplier identity is excluded from Inventory-facing exchange views.";
COMMENT ON COLUMN public.supplier_master.default_lead_days IS "General supplier lead-day reference from the Supplier sheet/master. SKU-specific committed lead time belongs in purchase_sku_supplier_policy.";

-- -----------------------------------------------------------------------------
-- VIEW: public.v_customer_360
CREATE OR REPLACE VIEW public.v_customer_360 AS
 WITH base AS (
         SELECT customer_master.contact_id,
            NULLIF(split_part(customer_master.party_key, ':'::text, 2), ''::text) AS stem,
            customer_master.lane,
            customer_master.branch_id,
            COALESCE(NULLIF(TRIM(BOTH FROM customer_master.display_name), ''::text), NULLIF(TRIM(BOTH FROM customer_master.company_name), ''::text), NULLIF(TRIM(BOTH FROM (customer_master.first_name || ' '::text) || COALESCE(customer_master.last_name, ''::text)), ''::text)) AS raw_name,
            NULLIF(TRIM(BOTH FROM customer_master.city_name), ''::text) AS city,
            NULLIF(TRIM(BOTH FROM customer_master.state_name), ''::text) AS state,
            NULLIF(TRIM(BOTH FROM customer_master.gstin), ''::text) AS gstin,
            NULLIF(TRIM(BOTH FROM customer_master.pan), ''::text) AS pan,
            NULLIF(TRIM(BOTH FROM customer_master.contact_type), ''::text) AS contact_type,
            customer_master.is_active,
            customer_master.last_modified_on,
            COALESCE(
                CASE
                    WHEN regexp_replace(COALESCE(customer_master.mobile_no, ''::text), '[^0-9]'::text, ''::text, 'g'::text) ~ '^[6-9][0-9]{9}$'::text THEN regexp_replace(customer_master.mobile_no, '[^0-9]'::text, ''::text, 'g'::text)
                    ELSE NULL::text
                END,
                CASE
                    WHEN regexp_replace(COALESCE(customer_master.whatsapp_no, ''::text), '[^0-9]'::text, ''::text, 'g'::text) ~ '^[6-9][0-9]{9}$'::text THEN regexp_replace(customer_master.whatsapp_no, '[^0-9]'::text, ''::text, 'g'::text)
                    ELSE NULL::text
                END,
                CASE
                    WHEN regexp_replace(COALESCE(customer_master.telephone, ''::text), '[^0-9]'::text, ''::text, 'g'::text) ~ '^[6-9][0-9]{9}$'::text THEN regexp_replace(customer_master.telephone, '[^0-9]'::text, ''::text, 'g'::text)
                    ELSE NULL::text
                END) AS own_phone,
                CASE
                    WHEN regexp_replace(COALESCE(customer_master.whatsapp_no, ''::text), '[^0-9]'::text, ''::text, 'g'::text) ~ '^[6-9][0-9]{9}$'::text THEN regexp_replace(customer_master.whatsapp_no, '[^0-9]'::text, ''::text, 'g'::text)
                    ELSE NULL::text
                END AS own_whatsapp
           FROM customer_master
          WHERE customer_master.lane = ANY (ARRAY['W'::text, 'WO'::text])
        ), feed AS (
         SELECT v_sales_data_all.customer_id_db_id::bigint AS contact_id,
            max(
                CASE
                    WHEN regexp_replace(COALESCE(v_sales_data_all.mobile_no, ''::text), '[^0-9]'::text, ''::text, 'g'::text) ~ '^[6-9][0-9]{9}$'::text THEN regexp_replace(v_sales_data_all.mobile_no, '[^0-9]'::text, ''::text, 'g'::text)
                    ELSE NULL::text
                END) AS feed_phone,
            max(NULLIF(v_sales_data_all.address, ''::text)) AS address,
            min(to_date(v_sales_data_all.date, 'DD/MM/YYYY'::text)) AS first_order,
            max(to_date(v_sales_data_all.date, 'DD/MM/YYYY'::text)) AS last_order,
            count(DISTINCT v_sales_data_all.voucher_no) AS orders_total,
            count(DISTINCT v_sales_data_all.voucher_no) FILTER (WHERE to_date(v_sales_data_all.date, 'DD/MM/YYYY'::text) >= (CURRENT_DATE - 30)) AS orders_30d,
            count(DISTINCT v_sales_data_all.voucher_no) FILTER (WHERE to_date(v_sales_data_all.date, 'DD/MM/YYYY'::text) >= (CURRENT_DATE - 90)) AS orders_90d,
            round(sum(NULLIF(regexp_replace(v_sales_data_all.net_amount, '[^0-9.\-]'::text, ''::text, 'g'::text), ''::text)::numeric)) AS value_total,
            round(sum(NULLIF(regexp_replace(v_sales_data_all.net_amount, '[^0-9.\-]'::text, ''::text, 'g'::text), ''::text)::numeric) FILTER (WHERE to_date(v_sales_data_all.date, 'DD/MM/YYYY'::text) >= (CURRENT_DATE - 90))) AS value_90d,
            count(DISTINCT v_sales_data_all.category_name) AS categories_bought,
            max(
                CASE
                    WHEN upper(COALESCE(v_sales_data_all.category_name, ''::text)) ~~ '%WINDING WIRE%'::text THEN 1
                    ELSE 0
                END) = 1 AS buys_winding_wire
           FROM v_sales_data_all
          WHERE v_sales_data_all.customer_id_db_id ~ '^[0-9]+$'::text AND v_sales_data_all.customer_id_db_id <> '0'::text
          GROUP BY (v_sales_data_all.customer_id_db_id::bigint)
        ), addr_phone AS (
         SELECT f_1.contact_id,
            ( SELECT regexp_replace(m.m[1], '[^0-9]'::text, ''::text, 'g'::text) AS regexp_replace
                   FROM regexp_matches(f_1.address, '(?<![0-9])([6-9][0-9]{4}[ \-]?[0-9]{5})(?![0-9])'::text) m(m)
                 LIMIT 1) AS address_phone
           FROM feed f_1
          WHERE f_1.address IS NOT NULL
        ), ledger AS (
         SELECT b.contact_id,
            b.stem,
            b.lane,
            b.branch_id,
            b.raw_name,
            b.city,
            b.state,
            b.gstin,
            b.pan,
            b.contact_type,
            b.is_active,
            b.last_modified_on,
            b.own_phone,
            b.own_whatsapp,
            f_1.feed_phone,
            f_1.address,
            ap.address_phone,
            f_1.first_order,
            f_1.last_order,
            f_1.orders_total,
            f_1.orders_30d,
            f_1.orders_90d,
            f_1.value_total,
            f_1.value_90d,
            f_1.categories_bought,
            f_1.buys_winding_wire
           FROM base b
             LEFT JOIN feed f_1 ON f_1.contact_id = b.contact_id
             LEFT JOIN addr_phone ap ON ap.contact_id = b.contact_id
        ), grp AS (
         SELECT COALESCE(ledger.stem, 'ID#'::text || min(ledger.contact_id)::text) AS party_stem,
            count(*) AS ledger_count,
            string_agg(DISTINCT ledger.contact_id::text, ', '::text ORDER BY (ledger.contact_id::text)) AS contact_ids,
            max(ledger.contact_id) FILTER (WHERE ledger.lane = 'W'::text) AS gst_contact_id,
            max(ledger.contact_id) FILTER (WHERE ledger.lane = 'WO'::text) AS nongst_contact_id,
            bool_or(ledger.lane = 'W'::text) AS has_gst_ledger,
            bool_or(ledger.lane = 'WO'::text) AS has_nongst_ledger,
            bool_or(ledger.branch_id = 31373) AS is_cri_entity,
            (array_agg(regexp_replace(ledger.raw_name, '^\s*\.\s*'::text, ''::text) ORDER BY (
                CASE
                    WHEN ledger.lane = 'W'::text THEN 0
                    ELSE 1
                END), (length(ledger.raw_name)) DESC))[1] AS business_name,
            (array_agg(ledger.city ORDER BY (
                CASE
                    WHEN ledger.city IS NULL THEN 1
                    ELSE 0
                END), (
                CASE
                    WHEN ledger.lane = 'W'::text THEN 0
                    ELSE 1
                END)))[1] AS city,
            (array_agg(ledger.state ORDER BY (
                CASE
                    WHEN ledger.state IS NULL THEN 1
                    ELSE 0
                END)))[1] AS state,
            count(DISTINCT ledger.city) AS city_variants,
            string_agg(DISTINCT ledger.city, ' / '::text ORDER BY ledger.city) AS city_list,
            max(ledger.gstin) AS gstin,
            max(ledger.pan) AS pan,
            max(ledger.contact_type) AS contact_type,
            bool_or(COALESCE(ledger.is_active, true)) AS is_active,
            max(ledger.last_modified_on) AS last_modified_on,
            (array_agg(ledger.own_phone ORDER BY ledger.own_phone) FILTER (WHERE ledger.own_phone IS NOT NULL))[1] AS p_master,
            (array_agg(ledger.own_whatsapp ORDER BY ledger.own_whatsapp) FILTER (WHERE ledger.own_whatsapp IS NOT NULL))[1] AS p_whatsapp,
            (array_agg(ledger.feed_phone ORDER BY ledger.feed_phone) FILTER (WHERE ledger.feed_phone IS NOT NULL))[1] AS p_feed,
            (array_agg(ledger.address_phone ORDER BY ledger.address_phone) FILTER (WHERE ledger.address_phone IS NOT NULL))[1] AS p_address,
            count(*) FILTER (WHERE ledger.own_phone IS NULL) AS ledgers_missing_phone,
            string_agg(DISTINCT ledger.contact_id::text, ', '::text) FILTER (WHERE ledger.own_phone IS NULL) AS ledger_ids_missing_phone,
            min(ledger.first_order) AS first_order,
            max(ledger.last_order) AS last_order,
            COALESCE(sum(ledger.orders_total), 0::numeric) AS orders_total,
            COALESCE(sum(ledger.orders_30d), 0::numeric) AS orders_30d,
            COALESCE(sum(ledger.orders_90d), 0::numeric) AS orders_90d,
            COALESCE(sum(ledger.value_total), 0::numeric) AS value_total,
            COALESCE(sum(ledger.value_90d), 0::numeric) AS value_90d,
            max(ledger.categories_bought) AS categories_bought,
            bool_or(COALESCE(ledger.buys_winding_wire, false)) AS buys_winding_wire
           FROM ledger
          GROUP BY (COALESCE(ledger.stem, 'ID#'::text || ledger.contact_id::text)), ledger.stem
        ), final AS (
         SELECT grp.party_stem,
            grp.business_name,
                CASE
                    WHEN grp.is_cri_entity THEN 'B - CRI entity'::text
                    ELSE 'A - Core'::text
                END AS entity,
                CASE
                    WHEN upper(grp.business_name) ~ 'REWIND|WINDING WORK'::text THEN 'Rewinding / service'::text
                    WHEN upper(grp.business_name) ~ 'SERVICE'::text THEN 'Service centre'::text
                    WHEN upper(grp.business_name) ~ 'BORE ?WELL|BOREWELL|DRILLING|RIG'::text THEN 'Borewell / installer'::text
                    WHEN upper(grp.business_name) ~ 'PUMP|MOTOR'::text THEN 'Pump trade'::text
                    WHEN upper(grp.business_name) ~ 'ENGINEER|ENGG|WORKS|INDUSTR|MFG|MANUFACT'::text THEN 'Engineering / manufacturer'::text
                    WHEN upper(grp.business_name) ~ 'TRADER|AGENC|ENTERPRIS|STORE|MARKETING|DISTRIBUT|CORPORATION|TRADING'::text THEN 'Trader / dealer'::text
                    WHEN upper(grp.business_name) ~ 'ELECTRIC|ELECTRO'::text THEN 'Electrical'::text
                    ELSE 'Unclassified'::text
                END AS segment,
            grp.city,
            grp.state,
            grp.city_variants,
            grp.city_list,
            grp.ledger_count,
            grp.contact_ids,
            grp.gst_contact_id,
            grp.nongst_contact_id,
            grp.has_gst_ledger,
            grp.has_nongst_ledger,
                CASE
                    WHEN grp.has_gst_ledger AND grp.has_nongst_ledger THEN 'BOTH'::text
                    WHEN grp.has_gst_ledger THEN 'GST only'::text
                    ELSE 'Non-GST only'::text
                END AS lane_coverage,
            grp.gstin,
            grp.pan,
            grp.contact_type,
            grp.is_active,
            grp.last_modified_on,
            COALESCE(grp.p_master, grp.p_feed, grp.p_address) AS phone,
            grp.p_whatsapp AS whatsapp,
                CASE
                    WHEN grp.p_master IS NOT NULL THEN 'MASTER'::text
                    WHEN grp.p_feed IS NOT NULL THEN 'SALES_FEED'::text
                    WHEN grp.p_address IS NOT NULL THEN 'ADDRESS_TEXT'::text
                    ELSE 'NONE'::text
                END AS phone_source,
            grp.p_master IS NOT NULL OR grp.p_feed IS NOT NULL AS phone_verified,
            grp.ledgers_missing_phone,
            grp.ledger_ids_missing_phone,
                CASE
                    WHEN grp.ledger_count > 1 AND grp.city_variants > 1 THEN true
                    ELSE false
                END AS city_conflict,
                CASE
                    WHEN grp.ledger_count <= 1 THEN 'HIGH - single ledger'::text
                    WHEN upper(grp.business_name) !~ 'PUMP|MOTOR|ELECTRIC|ENGINEER|ENGG|WORKS|INDUSTR|TRADER|AGENC|ENTERPRIS|STORE|SERVICE|REWIND|CORPORAT|TRADING|MARKETING|DISTRIBUT|WIRE|TECH|BORE|MACHIN|STEEL|COIL|COMPANY|AQUA'::text AND grp.city_variants > 1 THEN 'REVIEW - personal name and different cities, confirm before merging'::text
                    WHEN upper(grp.business_name) !~ 'PUMP|MOTOR|ELECTRIC|ENGINEER|ENGG|WORKS|INDUSTR|TRADER|AGENC|ENTERPRIS|STORE|SERVICE|REWIND|CORPORAT|TRADING|MARKETING|DISTRIBUT|WIRE|TECH|BORE|MACHIN|STEEL|COIL|COMPANY|AQUA'::text THEN 'MEDIUM - personal name, same city'::text
                    ELSE 'HIGH'::text
                END AS link_confidence,
            grp.first_order,
            grp.last_order,
                CASE
                    WHEN grp.last_order IS NULL THEN NULL::integer
                    ELSE CURRENT_DATE - grp.last_order
                END AS days_since_last_order,
            grp.orders_total,
            grp.orders_30d,
            grp.orders_90d,
            grp.value_total,
            grp.value_90d,
            grp.categories_bought,
            grp.buys_winding_wire,
                CASE
                    WHEN grp.last_order IS NULL THEN 'NO ORDERS IN FEED'::text
                    WHEN (CURRENT_DATE - grp.last_order) <= 30 THEN 'ACTIVE'::text
                    WHEN (CURRENT_DATE - grp.last_order) <= 60 THEN 'SLIPPING'::text
                    WHEN (CURRENT_DATE - grp.last_order) <= 120 THEN 'AT RISK'::text
                    ELSE 'DORMANT'::text
                END AS lifecycle
           FROM grp
        )
 SELECT party_stem,
    business_name,
    entity,
    segment,
    city,
    state,
    city_variants,
    city_list,
    ledger_count,
    contact_ids,
    gst_contact_id,
    nongst_contact_id,
    has_gst_ledger,
    has_nongst_ledger,
    lane_coverage,
    gstin,
    pan,
    contact_type,
    is_active,
    last_modified_on,
    phone,
    whatsapp,
    phone_source,
    phone_verified,
    ledgers_missing_phone,
    ledger_ids_missing_phone,
    city_conflict,
    link_confidence,
    first_order,
    last_order,
    days_since_last_order,
    orders_total,
    orders_30d,
    orders_90d,
    value_total,
    value_90d,
    categories_bought,
    buys_winding_wire,
    lifecycle,
        CASE
            WHEN phone_source = 'NONE'::text THEN '1. CALL TO COLLECT NUMBER'::text
            WHEN phone_source = 'ADDRESS_TEXT'::text THEN '2. VERIFY ADDRESS-DERIVED NUMBER'::text
            WHEN ledgers_missing_phone > 0 THEN '3. PUSH NUMBER TO VASY LEDGER'::text
            WHEN city IS NULL THEN '4. ADD CITY'::text
            WHEN city_conflict THEN '5. RESOLVE CITY VARIANT'::text
            ELSE '6. OK'::text
        END AS next_data_action
   FROM final f;
;
COMMENT ON VIEW public.v_customer_360 IS "One row per business. Merges GST (W) and non-GST (WO) Vasy ledgers on the party_key stem, resolves the best available phone (own ledger > twin ledger > sales feed > address text), and attaches activity from sales_data. Read only; no raw table is modified. ADDRESS_TEXT phones are unverified. Sales activity only covers the period present in sales_data - \"NO ORDERS IN FEED\" does not mean the customer never bought.";

-- -----------------------------------------------------------------------------
-- VIEW: public.v_customer_fy2627
CREATE OR REPLACE VIEW public.v_customer_fy2627 AS
 SELECT COALESCE(vt_party_name(contact_id, customer_name), 'WALK-IN (no account)'::text) AS customer,
    contact_id,
    count(*) AS invoices,
    round(sum(total)) AS billed,
    round(sum(paid_amount)) AS received,
    round(sum(balance)) AS still_open,
    count(*) FILTER (WHERE balance > 0.01) AS open_invoices,
    min(sales_date) AS first_invoice,
    max(sales_date) AS last_invoice
   FROM sales_invoice i
  WHERE sales_date >= '2026-04-01'::date
  GROUP BY (COALESCE(vt_party_name(contact_id, customer_name), 'WALK-IN (no account)'::text)), contact_id;
;
COMMENT ON VIEW public.v_customer_fy2627 IS "This financial year per customer: billed, received, still open. FY2026-27\n   data is reliable; earlier years are not.";

-- -----------------------------------------------------------------------------
-- VIEW: public.v_inventory_exception_candidates
CREATE OR REPLACE VIEW public.v_inventory_exception_candidates AS
 WITH p AS (
         SELECT max(v_sales_all.sales_date) AS ref_date
           FROM v_sales_all
        ), tx AS (
         SELECT s.item_code_base AS parent_sku,
            s.sales_date,
            s.voucher_no,
            COALESCE(NULLIF(s.customer_party_key, ''::text), s.customer_id_db_id::text, 'ANON'::text) AS customer_key,
            max(s.customer_name_final) AS customer_name,
            sum(GREATEST(COALESCE(s.qty_num, 0::numeric), 0::numeric)) AS qty,
            sum(GREATEST(COALESCE(s.net_amount_num, 0::numeric), 0::numeric)) AS net_value
           FROM v_sales_all s
             CROSS JOIN p
          WHERE s.item_code_base IS NOT NULL AND s.sales_date > (p.ref_date - '1 year'::interval) AND COALESCE(s.qty_num, 0::numeric) > 0::numeric
          GROUP BY s.item_code_base, s.sales_date, s.voucher_no, (COALESCE(NULLIF(s.customer_party_key, ''::text), s.customer_id_db_id::text, 'ANON'::text))
        ), stats AS (
         SELECT tx.parent_sku,
            percentile_cont(0.25::double precision) WITHIN GROUP (ORDER BY (tx.qty::double precision)) AS q1,
            percentile_cont(0.50::double precision) WITHIN GROUP (ORDER BY (tx.qty::double precision)) AS med,
            percentile_cont(0.75::double precision) WITHIN GROUP (ORDER BY (tx.qty::double precision)) AS q3,
            count(*) AS n
           FROM tx
          GROUP BY tx.parent_sku
        ), scored AS (
         SELECT t.parent_sku,
            t.sales_date,
            t.voucher_no,
            t.customer_key,
            t.customer_name,
            t.qty,
            t.net_value,
            s.med,
            s.q1,
            s.q3,
            s.q3 - s.q1 AS iqr,
            s.n,
                CASE
                    WHEN s.med > 0::double precision THEN t.qty::double precision / s.med
                    ELSE NULL::double precision
                END AS qty_vs_median
           FROM tx t
             JOIN stats s USING (parent_sku)
        )
 SELECT md5(concat_ws('|'::text, parent_sku, sales_date::text, COALESCE(voucher_no, ''::text), customer_key, qty::text)) AS transaction_key,
    parent_sku,
    sales_date,
    voucher_no,
    customer_key,
    customer_name,
    qty,
    net_value,
    med,
    q1,
    q3,
    iqr,
    n AS sample_count,
        CASE
            WHEN n >= 8 AND qty::double precision > (q3 + 3::double precision * iqr) AND COALESCE(qty_vs_median, 0::double precision) >= 5::double precision THEN 'IQR-extreme'::text
            WHEN n >= 8 AND qty::double precision > (q3 + 1.5::double precision * iqr) AND COALESCE(qty_vs_median, 0::double precision) >= 5::double precision THEN 'IQR+median'::text
            WHEN n >= 8 AND COALESCE(qty_vs_median, 0::double precision) >= 10::double precision THEN '10x-median'::text
            ELSE NULL::text
        END AS detection_method,
    qty_vs_median,
        CASE
            WHEN n >= 8 AND qty::double precision > (q3 + 3::double precision * iqr) AND COALESCE(qty_vs_median, 0::double precision) >= 10::double precision THEN 'High'::text
            WHEN n >= 8 AND (qty::double precision > (q3 + 1.5::double precision * iqr) OR COALESCE(qty_vs_median, 0::double precision) >= 10::double precision) THEN 'Medium'::text
            ELSE 'Low'::text
        END AS review_priority
   FROM scored
  WHERE n >= 8 AND (qty::double precision > (q3 + 1.5::double precision * iqr) AND COALESCE(qty_vs_median, 0::double precision) >= 5::double precision OR COALESCE(qty_vs_median, 0::double precision) >= 10::double precision);
;
COMMENT ON VIEW public.v_inventory_exception_candidates IS "Statistical candidates only. They do not alter normalized demand until reviewed in inventory_demand_exception_review.";

-- -----------------------------------------------------------------------------
-- VIEW: public.v_inventory_to_purchase
CREATE OR REPLACE VIEW public.v_inventory_to_purchase AS
 SELECT i.parent_sku,
    i.product_name,
    i.category,
    i.subcategory,
    i.brand,
    i.as_of_date,
    i.source_max_sales_date,
    i.demand_30d,
    i.demand_90d,
    i.demand_3m,
    i.demand_6m,
    i.demand_12m,
    i.demand_24m,
    i.avg_3m,
    i.avg_6m,
    i.avg_12m,
    i.avg_24m,
    i.median_monthly_12m,
    i.active_months_12m,
    i.transactions_12m,
    i.days_since_last_sale,
    i.baseline_demand_12m,
    i.abc_class,
    i.abc_revenue_class,
    i.xyz_class,
    i.fsn_class,
    i.demand_pattern,
    i.trend_3v6_pct,
    i.trend_6v12_pct,
    i.yoy_pct,
    i.trend_class,
    i.unique_customers_12m,
    i.top1_customer_pct,
    i.top3_customer_pct,
    i.customer_concentration_class,
    i.anonymous_qty_pct,
    i.exceptional_order_count_12m,
    i.exceptional_qty_12m,
    i.exceptional_pct_12m,
    i.demand_confidence,
    i.new_sku_flag,
    i.reactivated_flag,
    sp.criticality,
    COALESCE(sp.service_level_target, s.default_service_level) AS service_level_target,
    COALESCE(sp.target_coverage_days, s.default_target_coverage_days) AS target_coverage_days,
    sp.min_base_stock_qty,
    sp.do_not_stock,
    sp.discontinue,
    sp.substitute_group,
    st.qty_total AS stock_qty_observed,
    st.loaded_at AS stock_loaded_at,
    COALESCE(sp.stock_reliable_override, s.stock_reliable) AS stock_data_reliable,
    s.use_stock_in_reorder AND COALESCE(sp.stock_reliable_override, s.stock_reliable) AS stock_allowed_in_reorder,
    COALESCE(po.open_po_qty, 0::numeric) AS open_po_qty,
    COALESCE(po.in_transit_qty, 0::numeric) AS in_transit_qty,
    COALESCE(po.pending_not_shipped_qty, 0::numeric) AS pending_not_shipped_qty,
    po.next_expected_receipt,
    po.median_first_receipt_lead_days,
    po.p90_first_receipt_lead_days,
    po.fill_rate_pct,
    po.otif_pct,
    po.partial_delivery_pct,
    po.supply_confidence,
    i.safety_stock_qty,
    i.reorder_point_qty,
    i.target_stock_qty,
    i.recommended_buy_qty,
    i.purchase_urgency,
    i.recommendation_reason
   FROM inventory_sku_analytics i
     CROSS JOIN inventory_settings s
     LEFT JOIN inventory_sku_policy sp ON sp.parent_sku = i.parent_sku
     LEFT JOIN v_stock_parent_current st ON st.parent_sku = i.parent_sku
     LEFT JOIN po_sku_analytics po ON po.parent_sku = i.parent_sku
  WHERE s.id = 1;
;
COMMENT ON VIEW public.v_inventory_to_purchase IS "Shared Inventory-to-Purchase demand, stock and replenishment feed. No supplier commercial data.";

-- -----------------------------------------------------------------------------
-- VIEW: public.v_po_line_execution
CREATE OR REPLACE VIEW public.v_po_line_execution AS
 WITH shipped AS (
         SELECT COALESCE(psl.po_line_key, pl_1.po_line_key) AS po_line_key,
            sum(COALESCE(psl.qty_shipped, 0::numeric)) AS qty_shipped,
            min(ps.shipped_date) AS first_shipped_date,
            max(ps.shipped_date) AS last_shipped_date,
            count(DISTINCT ps.shipment_id) AS shipment_count,
            min(ps.expected_delivery_date) AS next_expected_delivery
           FROM po_lines pl_1
             LEFT JOIN po_shipment_lines psl ON psl.po_line_key = pl_1.po_line_key
             LEFT JOIN po_shipments ps ON ps.shipment_id = psl.shipment_id
          GROUP BY (COALESCE(psl.po_line_key, pl_1.po_line_key))
        ), received AS (
         SELECT pl_1.po_line_key,
            sum(COALESCE(prl.accepted_qty, prl.received_qty, 0::numeric)) AS accepted_qty,
            sum(COALESCE(prl.rejected_qty, 0::numeric)) AS rejected_qty,
            sum(COALESCE(prl.returned_qty, 0::numeric)) AS returned_qty,
            min(pr.received_date) AS first_receipt_date,
            max(pr.received_date) AS last_receipt_date,
            count(DISTINCT pr.receipt_id) AS receipt_count
           FROM po_lines pl_1
             LEFT JOIN po_receipt_lines prl ON prl.po_line_key = pl_1.po_line_key
             LEFT JOIN po_receipts pr ON pr.receipt_id = prl.receipt_id
          GROUP BY pl_1.po_line_key
        )
 SELECT pl.po_line_key,
    pl.po_number,
    pl.request_line_id,
    pl.parent_sku,
    pl.item_code,
    pl.product_name,
    pl.lane,
    ph.supplier_key,
    ph.supplier_name,
    ph.status AS po_status,
    ph.created_at,
    ph.approved_at,
    ph.sent_at,
    ph.promised_date,
    ph.revised_promised_date,
    ph.closed_at,
    ph.cancelled_at,
    pl.ordered_qty,
    pl.cancelled_qty,
    GREATEST(pl.ordered_qty - COALESCE(pl.cancelled_qty, 0::numeric), 0::numeric) AS effective_order_qty,
    COALESCE(s.qty_shipped, 0::numeric) AS qty_shipped,
    COALESCE(r.accepted_qty, 0::numeric) AS accepted_received_qty,
    COALESCE(r.rejected_qty, 0::numeric) AS rejected_qty,
    COALESCE(r.returned_qty, 0::numeric) AS returned_qty,
    GREATEST(GREATEST(pl.ordered_qty - COALESCE(pl.cancelled_qty, 0::numeric), 0::numeric) - COALESCE(s.qty_shipped, 0::numeric), 0::numeric) AS pending_not_shipped_qty,
    GREATEST(COALESCE(s.qty_shipped, 0::numeric) - COALESCE(r.accepted_qty, 0::numeric), 0::numeric) AS in_transit_qty,
    GREATEST(GREATEST(pl.ordered_qty - COALESCE(pl.cancelled_qty, 0::numeric), 0::numeric) - COALESCE(r.accepted_qty, 0::numeric), 0::numeric) AS open_qty,
    s.first_shipped_date,
    s.last_shipped_date,
    s.shipment_count,
    s.next_expected_delivery,
    r.first_receipt_date,
    r.last_receipt_date,
    r.receipt_count,
        CASE
            WHEN ph.sent_at IS NOT NULL AND r.first_receipt_date IS NOT NULL THEN r.first_receipt_date - ph.sent_at::date
            ELSE NULL::integer
        END AS first_receipt_lead_days,
        CASE
            WHEN ph.sent_at IS NOT NULL AND r.last_receipt_date IS NOT NULL AND COALESCE(r.accepted_qty, 0::numeric) >= GREATEST(pl.ordered_qty - COALESCE(pl.cancelled_qty, 0::numeric), 0::numeric) THEN r.last_receipt_date - ph.sent_at::date
            ELSE NULL::integer
        END AS full_receipt_lead_days,
        CASE
            WHEN GREATEST(pl.ordered_qty - COALESCE(pl.cancelled_qty, 0::numeric), 0::numeric) > 0::numeric THEN 100.0 * COALESCE(r.accepted_qty, 0::numeric) / GREATEST(pl.ordered_qty - COALESCE(pl.cancelled_qty, 0::numeric), 0::numeric)
            ELSE NULL::numeric
        END AS fill_rate_pct,
        CASE
            WHEN COALESCE(r.accepted_qty, 0::numeric) >= GREATEST(pl.ordered_qty - COALESCE(pl.cancelled_qty, 0::numeric), 0::numeric) AND COALESCE(ph.revised_promised_date, ph.promised_date) IS NOT NULL AND r.last_receipt_date <= COALESCE(ph.revised_promised_date, ph.promised_date) THEN true
            WHEN r.last_receipt_date IS NOT NULL AND COALESCE(ph.revised_promised_date, ph.promised_date) IS NOT NULL THEN false
            ELSE NULL::boolean
        END AS otif_flag,
    COALESCE(s.shipment_count, 0::bigint) > 1 OR COALESCE(r.receipt_count, 0::bigint) > 1 AS partial_delivery_flag
   FROM po_lines pl
     JOIN po_headers ph ON ph.po_number = pl.po_number
     LEFT JOIN shipped s ON s.po_line_key = pl.po_line_key
     LEFT JOIN received r ON r.po_line_key = pl.po_line_key;
;
COMMENT ON VIEW public.v_po_line_execution IS "Canonical per-PO-line execution state used to calculate open qty, transit qty, lead time, fill rate, OTIF and partial-delivery metrics.";

-- -----------------------------------------------------------------------------
-- VIEW: public.v_purchase_action_queue
CREATE OR REPLACE VIEW public.v_purchase_action_queue AS
 SELECT i.parent_sku,
    i.product_name,
    i.category,
    i.brand,
    i.abc_class,
    i.xyz_class,
    i.fsn_class,
    i.demand_pattern,
    i.trend_class,
    i.avg_6m,
    i.baseline_demand_12m,
    i.demand_confidence,
    i.stock_qty_observed,
    i.stock_data_reliable,
    i.open_po_qty,
    i.in_transit_qty,
    i.recommended_buy_qty,
    i.purchase_urgency,
    i.recommendation_reason,
    p.last_purchase_date,
    p.last_purchase_qty,
    p.last_purchase_rate,
    p.avg_purchase_qty_12m,
    p.median_purchase_qty_12m,
    p.primary_supplier_key,
    p.primary_supplier_name,
    p.primary_supplier_pct,
    p.wavg_rate_12m,
    p.price_change_vs_wavg_12m_pct,
    p.supplier_count_12m,
    p.single_source,
    ss.median_lead_days,
    ss.p90_lead_days,
    ss.fill_rate_pct,
    ss.otif_pct,
    ss.partial_delivery_pct,
    COALESCE(psp.confirmed_moq, pp.default_moq, p.inferred_moq) AS planning_moq_qty,
    COALESCE(psp.pack_multiple, pp.default_pack_multiple, p.inferred_pack_multiple) AS planning_pack_multiple,
        CASE
            WHEN i.purchase_urgency = 'Critical'::text THEN 1
            WHEN i.purchase_urgency = 'High'::text THEN 2
            WHEN i.purchase_urgency = 'Medium'::text THEN 3
            WHEN i.purchase_urgency = 'Low'::text THEN 4
            ELSE 5
        END AS priority_sort
   FROM v_inventory_to_purchase i
     LEFT JOIN purchase_sku_analytics p ON p.parent_sku = i.parent_sku
     LEFT JOIN purchase_sku_supplier_analytics ss ON ss.parent_sku = p.parent_sku AND ss.supplier_key = p.primary_supplier_key
     LEFT JOIN purchase_sku_supplier_policy psp ON psp.parent_sku = p.parent_sku AND psp.supplier_key = p.primary_supplier_key
     LEFT JOIN purchase_sku_policy pp ON pp.parent_sku = i.parent_sku;
;
COMMENT ON VIEW public.v_purchase_action_queue IS "Purchase-only decision view joining Inventory need context with commercial purchase/supplier context.";

-- -----------------------------------------------------------------------------
-- VIEW: public.v_purchase_inventory_data_quality
CREATE OR REPLACE VIEW public.v_purchase_inventory_data_quality AS
 SELECT 'Purchase Register'::text AS area,
    'Missing Parent SKU'::text AS issue,
    count(*) AS affected_rows,
    'High'::text AS severity
   FROM v_purchase
  WHERE NULLIF(TRIM(BOTH FROM v_purchase.item_code_base), ''::text) IS NULL
UNION ALL
 SELECT 'Purchase Register'::text AS area,
    'Invalid/Missing Bill Date'::text AS issue,
    count(*) AS affected_rows,
    'High'::text AS severity
   FROM v_purchase
  WHERE v_purchase.bill_dt IS NULL
UNION ALL
 SELECT 'Purchase Register'::text AS area,
    'Non-positive Purchase Qty'::text AS issue,
    count(*) AS affected_rows,
    'Medium'::text AS severity
   FROM v_purchase
  WHERE COALESCE(v_purchase.qty_num, 0::numeric) <= 0::numeric
UNION ALL
 SELECT 'Purchase Register'::text AS area,
    'Missing/Zero Rate'::text AS issue,
    count(*) AS affected_rows,
    'Medium'::text AS severity
   FROM v_purchase
  WHERE COALESCE(v_purchase.rate_num, 0::numeric) <= 0::numeric
UNION ALL
 SELECT 'Sales'::text AS area,
    'Missing Parent SKU'::text AS issue,
    count(*) AS affected_rows,
    'High'::text AS severity
   FROM v_sales_all
  WHERE NULLIF(TRIM(BOTH FROM v_sales_all.item_code_base), ''::text) IS NULL
UNION ALL
 SELECT 'Sales'::text AS area,
    'Missing Sales Date'::text AS issue,
    count(*) AS affected_rows,
    'High'::text AS severity
   FROM v_sales_all
  WHERE v_sales_all.sales_date IS NULL
UNION ALL
 SELECT 'PO Mirror'::text AS area,
    'PO lines without Parent SKU'::text AS issue,
    count(*) AS affected_rows,
    'High'::text AS severity
   FROM po_lines
  WHERE NULLIF(TRIM(BOTH FROM po_lines.parent_sku), ''::text) IS NULL
UNION ALL
 SELECT 'PO Mirror'::text AS area,
    'Received Qty above Effective Order Qty'::text AS issue,
    count(*) AS affected_rows,
    'High'::text AS severity
   FROM v_po_line_execution
  WHERE v_po_line_execution.accepted_received_qty > v_po_line_execution.effective_order_qty
UNION ALL
 SELECT 'Inventory'::text AS area,
    'Stock reliability gate is OFF'::text AS issue,
        CASE
            WHEN inventory_settings.stock_reliable AND inventory_settings.use_stock_in_reorder THEN 0
            ELSE 1
        END::bigint AS affected_rows,
    'Info'::text AS severity
   FROM inventory_settings
  WHERE inventory_settings.id = 1
UNION ALL
 SELECT 'Inventory'::text AS area,
    'Unreviewed Exceptional-order Candidates'::text AS issue,
    count(*) AS affected_rows,
    'Medium'::text AS severity
   FROM v_inventory_exception_candidates c
  WHERE NOT (EXISTS ( SELECT 1
           FROM inventory_demand_exception_review r
          WHERE r.transaction_key = c.transaction_key));
;
COMMENT ON VIEW public.v_purchase_inventory_data_quality IS "Operational readiness checks for Purchase/Inventory analytics. Zero affected_rows means the check passes.";

-- -----------------------------------------------------------------------------
-- VIEW: public.v_purchase_to_inventory
CREATE OR REPLACE VIEW public.v_purchase_to_inventory AS
 SELECT p.parent_sku,
    p.purchase_qty_6m,
    p.purchase_qty_12m,
    p.purchase_qty_24m,
    p.purchase_events_12m,
    p.last_purchase_date,
    p.last_purchase_qty,
    p.avg_purchase_qty_12m,
    p.median_purchase_qty_12m,
    p.avg_days_between_purchases,
    p.median_days_between_purchases,
    po.median_first_receipt_lead_days,
    po.p90_first_receipt_lead_days,
    po.median_full_receipt_lead_days,
    po.p90_full_receipt_lead_days,
    po.lead_sd_days,
    po.lead_sample_count,
    po.fill_rate_pct,
    po.otif_pct,
    po.partial_delivery_pct,
    po.avg_lots_per_po,
    COALESCE(po.open_po_qty, 0::numeric) AS open_po_qty,
    COALESCE(po.in_transit_qty, 0::numeric) AS in_transit_qty,
    COALESCE(po.pending_not_shipped_qty, 0::numeric) AS pending_not_shipped_qty,
    po.next_expected_receipt,
    po.oldest_open_po_days,
    COALESCE(pp.default_moq, p.inferred_moq) AS planning_moq_qty,
    COALESCE(pp.default_pack_multiple, p.inferred_pack_multiple) AS planning_pack_multiple,
    COALESCE(pp.planning_lead_days_override, po.p90_first_receipt_lead_days, po.median_first_receipt_lead_days) AS planning_lead_days,
    COALESCE(pp.planning_supply_sources_override, po.active_supply_sources, p.supplier_count_12m) AS active_supply_sources,
    COALESCE(pp.single_source_override, po.single_source, p.single_source) AS single_source,
    COALESCE(pp.supply_risk_override,
        CASE
            WHEN COALESCE(pp.single_source_override, po.single_source, p.single_source) = true AND COALESCE(po.p90_first_receipt_lead_days, 0::numeric) >= 30::numeric THEN 'Critical'::text
            WHEN COALESCE(pp.single_source_override, po.single_source, p.single_source) = true THEN 'High'::text
            WHEN COALESCE(po.otif_pct, 100::numeric) < 70::numeric OR COALESCE(po.fill_rate_pct, 100::numeric) < 80::numeric THEN 'High'::text
            WHEN COALESCE(po.otif_pct, 100::numeric) < 85::numeric OR COALESCE(po.fill_rate_pct, 100::numeric) < 90::numeric THEN 'Medium'::text
            ELSE 'Low'::text
        END) AS supply_risk,
    po.supply_confidence,
    GREATEST(p.updated_at, COALESCE(po.updated_at, p.updated_at), COALESCE(pp.updated_at, p.updated_at)) AS updated_at
   FROM purchase_sku_analytics p
     LEFT JOIN po_sku_analytics po ON po.parent_sku = p.parent_sku
     LEFT JOIN purchase_sku_policy pp ON pp.parent_sku = p.parent_sku;
;
COMMENT ON VIEW public.v_purchase_to_inventory IS "Supplier-neutral, cost-free Purchase-to-Inventory supply feed.";

-- -----------------------------------------------------------------------------
-- VIEW: public.v_stock_parent_current
CREATE OR REPLACE VIEW public.v_stock_parent_current AS
 SELECT regexp_replace(TRIM(BOTH FROM item_code), '/+$'::text, ''::text) AS parent_sku,
    max(product_name) AS product_name,
    max(category) AS category,
    max(brand) AS brand,
    sum(COALESCE(qty_w, 0::numeric)) AS qty_w,
    sum(COALESCE(qty_wo, 0::numeric)) AS qty_wo,
    sum(COALESCE(qty_total, 0::numeric)) AS qty_total,
    max(loaded_at) AS loaded_at
   FROM stock_live
  WHERE NULLIF(TRIM(BOTH FROM item_code), ''::text) IS NOT NULL
  GROUP BY (regexp_replace(TRIM(BOTH FROM item_code), '/+$'::text, ''::text));
;
COMMENT ON VIEW public.v_stock_parent_current IS "Current stock_live grouped to Parent SKU. Stock is visibility-only until reliability gates are enabled.";

-- -----------------------------------------------------------------------------
-- FUNCTION: public.refresh_po_analytics
CREATE OR REPLACE FUNCTION public.refresh_po_analytics()
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_ref_date date;
  v_sku_rows bigint;
  v_supplier_rows bigint;
begin
  select coalesce(
    max(coalesce(sent_at::date, created_at::date)),
    current_date
  ) into v_ref_date
  from po_headers;

  delete from po_sku_analytics;

  insert into po_sku_analytics(
    parent_sku,as_of_date,po_count_12m,open_po_qty,in_transit_qty,pending_not_shipped_qty,
    received_qty_12m,median_first_receipt_lead_days,p90_first_receipt_lead_days,
    median_full_receipt_lead_days,p90_full_receipt_lead_days,lead_sd_days,lead_sample_count,
    fill_rate_pct,otif_pct,partial_delivery_pct,avg_lots_per_po,next_expected_receipt,
    oldest_open_po_days,active_supply_sources,single_source,supply_confidence,updated_at
  )
  with base as (
    select *
    from v_po_line_execution
    where parent_sku is not null
  ),
  po_lots as (
    select
      b.parent_sku,
      b.po_number,
      max(coalesce(b.shipment_count,0)) as lots
    from base b
    group by b.parent_sku,b.po_number
  ),
  lot_avg as (
    select parent_sku,avg(lots)::numeric avg_lots_per_po
    from po_lots
    group by parent_sku
  )
  select
    b.parent_sku,
    v_ref_date,
    count(distinct b.po_number) filter(
      where coalesce(b.sent_at::date,b.created_at::date) > v_ref_date-365
    )::bigint,
    sum(b.open_qty) filter(
      where coalesce(b.po_status,'') not in ('Closed','Cancelled')
    )::numeric,
    sum(b.in_transit_qty) filter(
      where coalesce(b.po_status,'') not in ('Closed','Cancelled')
    )::numeric,
    sum(b.pending_not_shipped_qty) filter(
      where coalesce(b.po_status,'') not in ('Closed','Cancelled')
    )::numeric,
    sum(b.accepted_received_qty) filter(
      where b.last_receipt_date > v_ref_date-365
    )::numeric,
    percentile_cont(0.50) within group(order by b.first_receipt_lead_days::double precision)
      filter(where b.first_receipt_lead_days is not null)::numeric,
    percentile_cont(0.90) within group(order by b.first_receipt_lead_days::double precision)
      filter(where b.first_receipt_lead_days is not null)::numeric,
    percentile_cont(0.50) within group(order by b.full_receipt_lead_days::double precision)
      filter(where b.full_receipt_lead_days is not null)::numeric,
    percentile_cont(0.90) within group(order by b.full_receipt_lead_days::double precision)
      filter(where b.full_receipt_lead_days is not null)::numeric,
    stddev_pop(b.first_receipt_lead_days) filter(where b.first_receipt_lead_days is not null)::numeric,
    count(b.first_receipt_lead_days)::bigint,
    case when sum(b.effective_order_qty) filter(
      where coalesce(b.sent_at::date,b.created_at::date) > v_ref_date-365
    ) > 0 then
      100*sum(least(b.accepted_received_qty,b.effective_order_qty)) filter(
        where coalesce(b.sent_at::date,b.created_at::date) > v_ref_date-365
      ) / nullif(sum(b.effective_order_qty) filter(
        where coalesce(b.sent_at::date,b.created_at::date) > v_ref_date-365
      ),0)
    end::numeric,
    100*avg((b.otif_flag::int)::numeric) filter(where b.otif_flag is not null),
    100*avg((b.partial_delivery_flag::int)::numeric) filter(
      where b.first_shipped_date is not null or b.first_receipt_date is not null
    ),
    la.avg_lots_per_po,
    min(b.next_expected_delivery) filter(
      where b.open_qty>0 and coalesce(b.po_status,'') not in ('Closed','Cancelled')
    ),
    max(v_ref_date-coalesce(b.sent_at::date,b.created_at::date)) filter(
      where b.open_qty>0
        and coalesce(b.po_status,'') not in ('Closed','Cancelled')
        and coalesce(b.sent_at::date,b.created_at::date) is not null
    )::int,
    count(distinct b.supplier_key) filter(
      where coalesce(b.sent_at::date,b.created_at::date) > v_ref_date-365
        and b.supplier_key is not null
    )::int,
    (count(distinct b.supplier_key) filter(
      where coalesce(b.sent_at::date,b.created_at::date) > v_ref_date-365
        and b.supplier_key is not null
    ) = 1),
    case
      when count(b.first_receipt_lead_days)>=20 then 'HIGH'
      when count(b.first_receipt_lead_days)>=5 then 'MEDIUM'
      when count(b.first_receipt_lead_days)>=1 then 'LOW'
      else 'NONE'
    end,
    now()
  from base b
  left join lot_avg la using(parent_sku)
  group by b.parent_sku,la.avg_lots_per_po;

  get diagnostics v_sku_rows = row_count;

  -- Supplier-level PO execution metrics are merged into the commercial table.
  with s as (
    select
      parent_sku,
      supplier_key,
      max(supplier_name) as supplier_name,
      count(distinct po_number) filter(
        where coalesce(sent_at::date,created_at::date)>v_ref_date-365
      )::bigint as po_count_12m,
      avg(first_receipt_lead_days) filter(where first_receipt_lead_days is not null)::numeric as avg_lead_days,
      percentile_cont(0.50) within group(order by first_receipt_lead_days::double precision)
        filter(where first_receipt_lead_days is not null)::numeric as median_lead_days,
      percentile_cont(0.75) within group(order by first_receipt_lead_days::double precision)
        filter(where first_receipt_lead_days is not null)::numeric as p75_lead_days,
      percentile_cont(0.90) within group(order by first_receipt_lead_days::double precision)
        filter(where first_receipt_lead_days is not null)::numeric as p90_lead_days,
      stddev_pop(first_receipt_lead_days) filter(where first_receipt_lead_days is not null)::numeric as lead_sd_days,
      count(first_receipt_lead_days)::bigint as lead_sample_count,
      case when sum(effective_order_qty) filter(
        where coalesce(sent_at::date,created_at::date)>v_ref_date-365
      )>0 then
        100*sum(least(accepted_received_qty,effective_order_qty)) filter(
          where coalesce(sent_at::date,created_at::date)>v_ref_date-365
        )/nullif(sum(effective_order_qty) filter(
          where coalesce(sent_at::date,created_at::date)>v_ref_date-365
        ),0)
      end::numeric as fill_rate_pct,
      100*avg((otif_flag::int)::numeric) filter(where otif_flag is not null) as otif_pct,
      100*avg((partial_delivery_flag::int)::numeric) filter(
        where first_shipped_date is not null or first_receipt_date is not null
      ) as partial_delivery_pct,
      case when sum(ordered_qty) filter(
        where coalesce(sent_at::date,created_at::date)>v_ref_date-365
      )>0 then
        100*sum(cancelled_qty) filter(
          where coalesce(sent_at::date,created_at::date)>v_ref_date-365
        )/nullif(sum(ordered_qty) filter(
          where coalesce(sent_at::date,created_at::date)>v_ref_date-365
        ),0)
      end::numeric as cancellation_pct,
      avg(coalesce(shipment_count,0))::numeric as avg_lots_per_po,
      sum(open_qty) filter(where coalesce(po_status,'') not in ('Closed','Cancelled'))::numeric as open_po_qty,
      sum(in_transit_qty) filter(where coalesce(po_status,'') not in ('Closed','Cancelled'))::numeric as in_transit_qty,
      sum(pending_not_shipped_qty) filter(where coalesce(po_status,'') not in ('Closed','Cancelled'))::numeric as pending_not_shipped_qty,
      min(next_expected_delivery) filter(
        where open_qty>0 and coalesce(po_status,'') not in ('Closed','Cancelled')
      ) as next_expected_receipt,
      max(v_ref_date-coalesce(sent_at::date,created_at::date)) filter(
        where open_qty>0
          and coalesce(po_status,'') not in ('Closed','Cancelled')
          and coalesce(sent_at::date,created_at::date) is not null
      )::int as oldest_open_po_days,
      case
        when count(first_receipt_lead_days)>=20 then 'HIGH'
        when count(first_receipt_lead_days)>=5 then 'MEDIUM'
        when count(first_receipt_lead_days)>=1 then 'LOW'
        else 'NONE'
      end as supply_confidence
    from v_po_line_execution
    where parent_sku is not null and supplier_key is not null
    group by parent_sku,supplier_key
  )
  insert into purchase_sku_supplier_analytics(
    parent_sku,supplier_key,supplier_name,as_of_date,
    po_count_12m,avg_lead_days,median_lead_days,p75_lead_days,p90_lead_days,
    lead_sd_days,lead_sample_count,fill_rate_pct,otif_pct,partial_delivery_pct,cancellation_pct,
    avg_lots_per_po,open_po_qty,in_transit_qty,pending_not_shipped_qty,next_expected_receipt,
    oldest_open_po_days,supply_confidence,updated_at
  )
  select
    parent_sku,supplier_key,supplier_name,v_ref_date,
    po_count_12m,avg_lead_days,median_lead_days,p75_lead_days,p90_lead_days,
    lead_sd_days,lead_sample_count,fill_rate_pct,otif_pct,partial_delivery_pct,cancellation_pct,
    avg_lots_per_po,coalesce(open_po_qty,0),coalesce(in_transit_qty,0),
    coalesce(pending_not_shipped_qty,0),next_expected_receipt,oldest_open_po_days,
    supply_confidence,now()
  from s
  on conflict(parent_sku,supplier_key) do update set
    supplier_name=coalesce(excluded.supplier_name,purchase_sku_supplier_analytics.supplier_name),
    po_count_12m=excluded.po_count_12m,
    avg_lead_days=excluded.avg_lead_days,
    median_lead_days=excluded.median_lead_days,
    p75_lead_days=excluded.p75_lead_days,
    p90_lead_days=excluded.p90_lead_days,
    lead_sd_days=excluded.lead_sd_days,
    lead_sample_count=excluded.lead_sample_count,
    fill_rate_pct=excluded.fill_rate_pct,
    otif_pct=excluded.otif_pct,
    partial_delivery_pct=excluded.partial_delivery_pct,
    cancellation_pct=excluded.cancellation_pct,
    avg_lots_per_po=excluded.avg_lots_per_po,
    open_po_qty=excluded.open_po_qty,
    in_transit_qty=excluded.in_transit_qty,
    pending_not_shipped_qty=excluded.pending_not_shipped_qty,
    next_expected_receipt=excluded.next_expected_receipt,
    oldest_open_po_days=excluded.oldest_open_po_days,
    supply_confidence=excluded.supply_confidence,
    updated_at=now();

  get diagnostics v_supplier_rows = row_count;

  update purchase_sku_analytics p
  set
    po_count_12m=po.po_count_12m,
    median_lead_days=po.median_first_receipt_lead_days,
    p90_lead_days=po.p90_first_receipt_lead_days,
    lead_sd_days=po.lead_sd_days,
    lead_sample_count=po.lead_sample_count,
    fill_rate_pct=po.fill_rate_pct,
    otif_pct=po.otif_pct,
    partial_delivery_pct=po.partial_delivery_pct,
    avg_lots_per_po=po.avg_lots_per_po,
    open_po_qty=coalesce(po.open_po_qty,0),
    in_transit_qty=coalesce(po.in_transit_qty,0),
    pending_not_shipped_qty=coalesce(po.pending_not_shipped_qty,0),
    next_expected_receipt=po.next_expected_receipt,
    oldest_open_po_days=po.oldest_open_po_days,
    effective_moq=coalesce(pp.default_moq,p.inferred_moq),
    effective_pack_multiple=coalesce(pp.default_pack_multiple,p.inferred_pack_multiple),
    supply_confidence=po.supply_confidence,
    supply_risk_class=coalesce(
      pp.supply_risk_override,
      case
        when coalesce(pp.single_source_override,po.single_source,p.single_source)=true
          and coalesce(po.p90_first_receipt_lead_days,0)>=30 then 'CRITICAL'
        when coalesce(pp.single_source_override,po.single_source,p.single_source)=true then 'HIGH'
        when coalesce(po.otif_pct,100)<70 or coalesce(po.fill_rate_pct,100)<80 then 'HIGH'
        when coalesce(po.otif_pct,100)<85 or coalesce(po.fill_rate_pct,100)<90 then 'MEDIUM'
        else 'LOW'
      end
    ),
    updated_at=now()
  from po_sku_analytics po
  left join purchase_sku_policy pp on pp.parent_sku=po.parent_sku
  where p.parent_sku=po.parent_sku;

  insert into analytics_refresh_log(
    dataset,started_at,finished_at,source_max_date,rows_written,status,details
  )
  values(
    'po_analytics',now(),now(),v_ref_date,v_sku_rows,'SUCCESS',
    jsonb_build_object('supplier_rows_touched',v_supplier_rows)
  );

  return jsonb_build_object(
    'ok',true,
    'as_of_date',v_ref_date,
    'po_sku_rows',v_sku_rows,
    'supplier_rows_touched',v_supplier_rows
  );
exception when others then
  insert into analytics_refresh_log(
    dataset,started_at,finished_at,source_max_date,rows_written,status,error_text,details
  )
  values(
    'po_analytics',now(),now(),v_ref_date,0,'FAILED',sqlerrm,'{}'::jsonb
  );
  raise;
end;
$function$


COMMIT;
